// Copies the compiled ABIs into packages/chain as typed `as const` modules, so viem infers
// argument and return types. Run after `forge build`: `pnpm --filter @stampd/contracts abis`.
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "..", "chain", "src", "abis");
const names = ["DemoUSD", "OutcomeTokens", "MarketHub", "MarketFactory", "Resolver"];

mkdirSync(outDir, { recursive: true });
const exports = [];
for (const name of names) {
  const artifact = JSON.parse(readFileSync(join(root, "out", `${name}.sol`, `${name}.json`), "utf8"));
  const ident = name[0].toLowerCase() + name.slice(1) + "Abi";
  writeFileSync(
    join(outDir, `${name}.ts`),
    `// Generated by packages/contracts/scripts/export-abis.mjs. Do not edit.\nexport const ${ident} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
  );
  exports.push(`export { ${ident} } from "./${name}";`);
}
writeFileSync(join(outDir, "index.ts"), exports.join("\n") + "\n");

// Deployment files (testnet/mainnet) travel with the chain package.
// Written as a TS module so the browser bundle needs no fs access.
const depSrc = join(root, "deployments");
const deployments = {};
if (existsSync(depSrc)) {
  for (const f of readdirSync(depSrc)) {
    if (!f.endsWith(".json")) continue;
    const d = JSON.parse(readFileSync(join(depSrc, f), "utf8"));
    deployments[d.chainId] = d;
  }
}
writeFileSync(
  join(root, "..", "chain", "src", "deployments.generated.ts"),
  `// Generated by packages/contracts/scripts/export-abis.mjs from packages/contracts/deployments/*.json.
` +
    `import type { Deployment } from "./deployments";

` +
    `export const DEPLOYMENTS: Record<number, Deployment> = ${JSON.stringify(deployments, null, 2)};
`,
);
console.log(`exported ${names.length} ABIs to ${outDir}`);
