// Generated by packages/contracts/scripts/export-abis.mjs from packages/contracts/deployments/*.json.
import type { Deployment } from "./deployments";

export const DEPLOYMENTS: Record<number, Deployment> = {
  "31337": {
    "chainId": 31337,
    "contracts": {
      "DemoUSD": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      "MarketFactory": "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
      "MarketHub": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
      "OutcomeTokens": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
      "Resolver": "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9"
    },
    "deployBlock": 0,
    "roles": {
      "admin": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
      "arbiter": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
      "creator": "0x70997970C51812dc3A010C7d01b50e0d17dc79C8",
      "faucetSigner": "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
      "resolver": "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
    }
  },
  "46630": {
    "chainId": 46630,
    "contracts": {
      "DemoUSD": "0xf16c78569a97B0bfED9aa6900E923f6F224b0597",
      "MarketFactory": "0x5954Fd59Fc88Aa1FdC7f4710DB6bA4f19815EfA2",
      "MarketHub": "0xb481764876992b1D70970FF22D6b04E21BB6444D",
      "OutcomeTokens": "0x8a440a4f2425AD82c8D8Cf178C0561BdB03EbedA",
      "Resolver": "0x9dCCE78575E8183953f9759CE73e8b3ef7529483"
    },
    "deployBlock": 126862739,
    "roles": {
      "admin": "0x9F220f524b978C45b246fde763b460FE3fAfd1bf",
      "arbiter": "0x9F220f524b978C45b246fde763b460FE3fAfd1bf",
      "creator": "0x01366783fD21c345b1bace7A77203ce15c24759c",
      "faucetSigner": "0x64CFD173cdeE9e84E382cCeEadF97F8472C8C73b",
      "resolver": "0x16D9d76ede51e6E22eF3BA1ACA3a83E823a44d6c"
    }
  }
};
